{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "eks-ebs-node-operator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "eks-ebs-node-operator.name" . }}
    helm.sh/chart: {{ include "eks-ebs-node-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  kind: ClusterRole
  name: {{ include "eks-ebs-node-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ include "eks-ebs-node-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
